### ISSUE TITLE
Unable to open files with associated application

### ISSUE THREAD

**Issue by x80486** [flathub/org.gnome.FileRoller#4]
I'm using GNOME `3.38` under Arch Linux. Currently, I'm unable to open any file under any archive.

I can tell that `Archive Manager` is unable to recognize the installed applications (Flatpaks or packages/native) associated with a given file type in order to open it.

![image](https://user-images.githubusercontent.com/34633617/95992913-77eef200-0dfc-11eb-9088-0385d28cef1e.png)

Not sure if it is possible to fix this one, but filing it just in case.

**Comment by JayDoubleu** [comment]
This is quite important to implement, in most cases I would open an archive in file-roller and open it with something like gedit etc.

**Comment by A6GibKm** [comment]
See https://gitlab.gnome.org/GNOME/file-roller/-/issues/105

**Comment by salim-b** [comment]
This problem has recently (I think with the update to v44.4 2 weeks ago) reappeared for me:

[Screencast from 2024-12-08 19-03-50.webm](https://github.com/user-attachments/assets/5fdb9cde-7d1d-492b-b321-ea3e7df6c79e)

I didn't change any relevant config AFAICT. Anyone else suffering from this?

I'm using [Bluefin](https://docs.projectbluefin.io/) which is based on Fedora Silverblue.

---

Addendum: I think the issue re-appearing is due to [this upstream change](https://gitlab.gnome.org/GNOME/file-roller/-/commit/2d249ad51ef0d84c62fbfa3c54bf6f644033ce52). Since this Flatpak is not maintained by the app author(s), should I still report this upstream?

**Comment by A6GibKm** [comment]
> This problem has recently (I think with the update to v44.4 2 weeks ago) reappeared for me:
> Screencast.from.2024-12-08.19-03-50.webm
> 
> I didn't change any relevant config AFAICT. Anyone else suffering from this?
> 
> I'm using [Bluefin](https://docs.projectbluefin.io/) which is based on Fedora Silverblue.
> 
> Addendum: I think the issue re-appearing is due to [this upstream change](https://gitlab.gnome.org/GNOME/file-roller/-/commit/2d249ad51ef0d84c62fbfa3c54bf6f644033ce52). Since this Flatpak is not maintained by the app author(s), should I still report this upstream?

Thanks for the report, the default was silently changed upstream https://gitlab.gnome.org/GNOME/file-roller/-/commit/2d249ad51ef0d84c62fbfa3c54bf6f644033ce52, the PR https://github.com/flathub/org.gnome.FileRoller/pull/38 should fix it here.

**Comment by yatian-liu** [comment]
Somehow this issue re-appears again for me. Did the upstream developers disable the native app chooser again for some reason? In addition I think the claim in [this upstream change](https://gitlab.gnome.org/GNOME/file-roller/-/commit/2d249ad51ef0d84c62fbfa3c54bf6f644033ce52) that using the native app chooser "adds no real value" is a bit arrogant since it solves this issue here 🤔

My File Roller flatpak version is 44.5, and I installed it via Fedora's repo `oci+https://registry.fedoraproject.org`. If additional information is needed please tell me and I'll add them soon.

![Image](https://github.com/user-attachments/assets/08025acc-4c0b-413e-88f7-b4777727f229)
![Image](https://github.com/user-attachments/assets/f94f3b9f-b8db-4c66-af70-3b8da6738ca0)

**Comment by A6GibKm** [comment]
The fix was only in the version at flathub, the version at fedora repos is not the same.  I would advise to not use the fedora flatpak repo, it's just a big source of bugs.

**Comment by yatian-liu** [comment]
> The fix was only in the version at flathub, the version at fedora repos is not the same. I would advise to not use the fedora flatpak repo, it's just a big source of bugs.

I've tried the flathub version and it indeed works! Thank you! I'm using Fedora Silverblue so I intially thought that the fedora repo might have better compatibility with the OS...
